[tox]
skip_missing_interpreters = true
envlist = py313, lint, formatcheck

[testenv]
description = run the tests
deps =
    pytest
commands =
    pytest -vv {posargs}

[testenv:lint]
description = run the linting toolchain
skip_install = true
deps =
    ruff
commands =
    ruff check wispy tests

[testenv:formatcheck]
description = run the format check toolchain
skip_install = true
deps =
    ruff
commands =
    ruff format --check wispy tests

[testenv:format]
description = run the format toolchain
skip_install = true
deps =
    ruff
commands =
    ruff format wispy tests
