#!/bin/bash

#DEBHELPER#

# function to check if a given path is a symlink
function isValidSymlink() {
    if [ -L "$1" ]; then
        return 0
    else
        return 1
    fi
}

# Stop Grafana service if it is running
echo "Stopping Grafana service ..."
/bin/systemctl is-active --quiet grafana-server.service && /bin/systemctl stop grafana-server.service

# Backup current Grafana config file before we install ours
GRAFANA_CONF=/etc/grafana/grafana.ini    
if ! isValidSymlink $GRAFANA_CONF; then
    if [ -f "$GRAFANA_CONF" ]; then
        TSTAMP=`date '+%s'`
        NEW_CONF="$GRAFANA_CONF.$TSTAMP"
        echo "Existing grafana.conf detected; backing it up and moving it to $NEW_CONF..."
        mv $GRAFANA_CONF $NEW_CONF
    fi
    echo "Linking our grafana.ini config ..."
    ln -s /etc/wlanpi-grafana/grafana.ini $GRAFANA_CONF
fi

# Install plugins
echo "Installing Grafana plugins"
grafana-cli plugins install ae3e-plotly-panel

# Change default admin/admin credentials to admin/wlanpi, but do it only once at package first installation time, not when user upgrades package
if [ ! -f /opt/wlanpi-grafana/pwd-changed ]; then
    /usr/sbin/grafana-cli admin reset-admin-password wlanpi && touch /opt/wlanpi-grafana/pwd-changed
fi
