#!/bin/bash

#DEBHELPER#

# Install plugins
echo "Installing Grafana plugins"
grafana-cli plugins install ae3e-plotly-panel

# Restart Grafana service
echo "Restarting Grafana server service"
/bin/systemctl stop grafana-server
/bin/systemctl start grafana-server

# Enable Grafana service
echo "Enabling Grafana server service"
/bin/systemctl enable grafana-server
