#!/bin/bash

#DEBHELPER#

# Add Grafana repo
if [ ! -f /etc/apt/sources.list.d/grafana.list ]; then
    echo "Adding grafana repo"
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
fi

# Install Grafana
if ! dpkg-query -l grafana >/dev/null 2>&1; then
    echo "Installing Grafana package"
    sudo apt update && sudo apt install -y grafana
fi

# Enable Grafana web UI port
echo "Enabling TCP port 3000"
sudo ufw allow 3000/tcp

# Start Grafana service
echo "Enabling grafana-server service"
sudo /bin/systemctl enable grafana-server
