#!/bin/bash

echo "Executing preinst script"

# Backup current Grafana config file before we install ours
GRAFANA_CONF=/etc/grafana/grafana.ini    
if [ -f "$GRAFANA_CONF" ]; then
    TSTAMP=`date '+%s'`
    NEW_CONF="$GRAFANA_CONF.$TSTAMP"
    echo "Existing grafana.ini detected. Backing it up and moving it to $NEW_CONF..."
    mv "$GRAFANA_CONF" "$NEW_CONF"
fi

#DEBHELPER#
